export const sectionsSuperCarry = [
    {
      title: "Measurement",
      rows: [
        {
          id: 1,
          name: "Height",
          value: "1883 mm",
          value2: "1883 mm",
          value3: "1883 mm",
          value4: "1883 mm",
        },
        {
          id: 2,
          name: "Wheel Base",
          value: "2110 mm",
          value2: "2110 mm",
          value3: "2110 mm",
          value4: "2110 mm",
        },
        {
          id: 3,
          name: "Length",
          value: "3800 mm",
          value2: "3800 mm",
          value3: "3800 mm",
          value4: "3800 mm",
        },
        {
          id: 4,
          name: "Front Track",
          value: "1345 mm",
          value2: "1345 mm",
          value3: "1345 mm",
          value4: "1345 mm",
        },
        {
          id: 5,
          name: "Width of Deck",
          value: "1488 mm",
          value2: "1488 mm",
          value3: "NA",
          value4: "NA",
        },
        {
          id: 6,
          name: "Turning Radius",
          value: "4.3 m",
          value2: "4.3 m",
          value3: "4.3 m",
          value4: "4.3 m",
        },
        {
          id: 7,
          name: "Width",
          value: "1562 mm",
          value2: "1562 mm",
          value3: "1562 mm",
          value4: "1562 mm",
        },
        {
          id: 8,
          name: "Rear Track",
          value: "1330 mm",
          value2: "1330 mm",
          value3: "1330 mm",
          value4: "1330 mm",
        },
        {
          id: 9,
          name: "Length of Deck",
          value: "2183 mm",
          value2: "2183 mm",
          value3: "NA",
          value4: "NA",
        },
        {
          id: 10,
          name: "Height of Deck",
          value: "300 mm",
          value2: "300 mm",
          value3: "NA",
          value4: "NA",
        },
      ],
    },
    {
      title: "Transmission",
      rows: [
        {
          id: 1,
          name: "Gearbox",
          value: "5 Forward and 1 Reverse",
          value2: "5 Forward and 1 Reverse",
          value3: "5 Forward and 1 Reverse",
          value4: "5 Forward and 1 Reverse",
        },
        {
          id: 2,
          name: "TYPE",
          value: "5MT",
          value2: "5MT",
          value3: "5MT",
          value4: "5MT",
        },
        {
          id: 3,
          name: "Clutch",
          value: "Single Plate Dry Friction",
          value2: "Single Plate Dry Friction",
          value3: "Single Plate Dry Friction",
          value4: "Single Plate Dry Friction",
        },
      ],
    },
    {
      title: "Suspension and Steering",
      rows: [
        {
          id: 1,
          name: "Steering",
          value: "Manual-Rack and Pinion",
          value2: "Manual-Rack and Pinion",
          value3: "Manual-Rack and Pinion",
          value4: "Manual-Rack and Pinion",
        },
        {
          id: 2,
          name: "Rear",
          value: "Leaf Spring Rigid Axle",
          value2: "Leaf Spring Rigid Axle",
          value3: "Leaf Spring Rigid Axle",
          value4: "Leaf Spring Rigid Axle",
        },
        {
          id: 3,
          name: "Front",
          value: "MacPherson strut with Coil Spring",
          value2: "MacPherson strut with Coil Spring",
          value3: "MacPherson strut with Coil Spring",
          value4: "MacPherson strut with Coil Spring",
        },
      ],
    },
    {
      title: "Capacity",
      rows: [
        {
          id: 1,
          name: "Seating Capacity",
          value: "Driver + 1",
          value2: "Driver + 1",
          value3: "Driver + 1",
          value4: "Driver + 1",
        },
        {
          id: 2,
          name: "Fuel Tank",
          value: "30 L",
          value2:
            "CNG Cylinder (Water Equivalent) = 70L (35L x 2) Gasoline = 5L (For Emergency Use)",
          value3: "30 L",
          value4:
            "CNG Cylinder (Water Equivalent) = 70L (35L x 2) Gasoline = 5L (For Emergency Use)",
        },
      ],
    },
    {
      title: "Brake",
      rows: [
        {
          id: 1,
          name: "Front",
          value: "Ventilated Disc Brake",
          value2: "Ventilated Disc Brake",
          value3: "Ventilated Disc Brake",
          value4: "Ventilated Disc Brake",
        },
        {
          id: 2,
          name: "Rear",
          value: "Drum Brake",
          value2: "Drum Brake",
          value3: "Drum Brake",
          value4: "Drum Brake",
        },
        {
          id: 3,
          name: "Brake Control valve",
          value: "LSPV",
          value2: "LSPV",
          value3: "LSPV",
          value4: "LSPV",
        },
      ],
    },
    {
      title: "Performance",
      rows: [
        {
          id: 1,
          name: "Gradeability",
          value: "34%",
          value2: "34%",
          value3: "34%",
          value4: "34%",
        },
        {
          id: 2,
          name: "Top Speed",
          value: "80 Km/h",
          value2: "80 Km/h",
          value3: "80 Km/h",
          value4: "80 Km/h",
        },
      ],
    },
    {
      title: "Wheel and Tyre",
      rows: [
        {
          id: 1,
          name: "Tyre",
          value: "155R13 LT 8PR",
          value2: "155R13 LT 8PR",
          value3: "155R13 LT 8PR",
          value4: "155R13 LT 8PR",
        },
      ],
    },
    {
      title: "Weight",
      rows: [
        {
          id: 1,
          name: "GVW",
          value: "1600 Kg",
          value2: "1600 Kg",
          value3: "1600 Kg",
          value4: "1600 Kg",
        },
        {
          id: 2,
          name: "Kerb",
          value: "860 Kg",
          value2: "975 kg",
          value3: "765 Kg",
          value4: "765 Kg",
        },
        {
          id: 3,
          name: "Payload",
          value: "740 Kg",
          value2: "625 Kg",
          value3: "NA",
          value4: "NA",
        },
      ],
    },
    {
      title: "Other Specifications",
      rows: [
        {
          id: 1,
          name: "Maximum Power",
          value: "59.4KW (80.7PS) @6000 rpm",
          value2: "52.7KW (71.6PS) @6000 rpm",
          value3: "59.4KW (80.7PS) @6000 rpm",
          value4: "52.7KW (71.6PS) @6000 rpm",
        },
        {
          id: 2,
          name: "Engine",
          value: "Advanced K-Series Dual Jet, Dual VVT",
          value2: "Advanced K-Series Dual Jet, Dual VVT",
          value3: "Advanced K-Series Dual Jet, Dual VVT",
          value4: "Advanced K-Series Dual Jet, Dual VVT",
        },
        {
          id: 3,
          name: "Fuel Distribution",
          value: "MPFI",
          value2: "MPFI",
          value3: "MPFI",
          value4: "MPFI",
        },
        {
          id: 4,
          name: "Maximum Torque",
          value: "104.4 Nm @2900 rpm",
          value2: "95 Nm @2800 rpm",
          value3: "104.4 Nm @2900 rpm",
          value4: "95 Nm @2800 rpm",
        },
        {
          id: 5,
          name: "Engine Capacity",
          value: "1197 cc",
          value2: "1197 cc",
          value3: "1197 cc",
          value4: "1197 cc",
        },
      ],
    },
  ];